// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEgP2CNCGmyMnDbYpLjLR_4ZFktaR8Jg',
    appId: '1:36237181800:web:7a751366c5dce1bea70cdd',
    messagingSenderId: '36237181800',
    projectId: 'flutterchatapp-54763',
    authDomain: 'flutterchatapp-54763.firebaseapp.com',
    storageBucket: 'flutterchatapp-54763.appspot.com',
    measurementId: 'G-P6FGGHBHRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkasZ3BOZy4ycOwOaYtdfRNw81xjBUBhU',
    appId: '1:36237181800:android:0302655efec830a6a70cdd',
    messagingSenderId: '36237181800',
    projectId: 'flutterchatapp-54763',
    storageBucket: 'flutterchatapp-54763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMPIiFkDwrsXw-QkplhLdt8JU7ErhAL0',
    appId: '1:36237181800:ios:598374f3ef46476aa70cdd',
    messagingSenderId: '36237181800',
    projectId: 'flutterchatapp-54763',
    storageBucket: 'flutterchatapp-54763.appspot.com',
    iosClientId: '36237181800-v9dtfmhthl2pcaecpnnqmpo135nsouur.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiMPIiFkDwrsXw-QkplhLdt8JU7ErhAL0',
    appId: '1:36237181800:ios:4855582c6816a10aa70cdd',
    messagingSenderId: '36237181800',
    projectId: 'flutterchatapp-54763',
    storageBucket: 'flutterchatapp-54763.appspot.com',
    iosClientId: '36237181800-bvvt3m720lf8g44aq7dc5iej3ck19n1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
